'use strict';
const api='../backend/tags.php'; let catalog=[],records=[];
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(msg){$('tagToast').textContent=msg;$('tagToast').classList.add('show');setTimeout(()=>$('tagToast').classList.remove('show'),2500)}
async function request(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Request failed');return j.data}
async function loadCatalog(){const d=await request(api);catalog=d.tags||[];$('tagCatalog').innerHTML=catalog.map(t=>`<span class="tag-chip" style="--tag-color:${esc(t.color)}"><i class="fa-solid fa-tag"></i>${esc(t.name)} <small>${t.usage_count}</small><button title="Edit" onclick="editTag(${t.tag_id})"><i class="fa-solid fa-pen"></i></button>${+t.is_predefined?'<span class="tag-fixed">PRESET</span>':`<button title="Delete" onclick="deleteTag(${t.tag_id})"><i class="fa-solid fa-xmark"></i></button>`}</span>`).join('')}
async function loadRecords(){const type=$('recordType').value;const d=await request(`${api}?records=1&object_type=${encodeURIComponent(type)}`);records=d.records||[];renderRecords()}
async function loadRecent(){const d=await request(`${api}?recent=1&limit=30`);const labels={resident:'Resident',street:'Street',resident_report:'Incident / Disaster Report',welfare_action_plan:'Assistance Plan'};$('recentTags').innerHTML=(d.assignments||[]).map(a=>`<tr><td><span class="tag-chip" style="--tag-color:${esc(a.color)}"><i class="fa-solid fa-tag"></i>${esc(a.name)}</span></td><td>${esc(labels[a.object_type]||a.object_type)}</td><td>#${a.record_id} ${esc(a.record_label||'')}</td><td>${esc(a.assigned_by_name||'System')}</td><td>${new Date(a.assigned_at.replace(' ','T')).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="5">No tag assignments yet.</td></tr>'}
function renderRecords(){const q=$('recordSearch').value.trim().toLowerCase();const rows=records.filter(r=>!q||r.record_label.toLowerCase().includes(q)||(r.tags||[]).some(t=>t.name.toLowerCase().includes(q)));$('recordList').innerHTML=rows.map(r=>`<div class="record-row"><strong>#${r.record_id} ${esc(r.record_label)}</strong><select multiple size="3" data-id="${r.record_id}" aria-label="Tags for ${esc(r.record_label)}">${catalog.map(t=>`<option value="${esc(t.name)}" ${(r.tags||[]).some(x=>+x.tag_id===+t.tag_id)?'selected':''}>${esc(t.name)}</option>`).join('')}</select><button class="tag-btn" onclick="saveAssignment(this,${r.record_id})">Save</button></div>`).join('')||'<p>No matching records.</p>'}
window.editTag=id=>{const t=catalog.find(x=>+x.tag_id===+id);$('tagId').value=id;$('tagName').value=t.name;$('tagColor').value=t.color;$('tagCancel').hidden=false;$('tagName').focus()};
window.deleteTag=async id=>{if(!confirm('Delete this custom tag and remove all its assignments?'))return;try{await request(`${api}?id=${id}`,{method:'DELETE'});toast('Tag deleted.');await loadCatalog();await loadRecords();await loadRecent()}catch(e){toast(e.message)}};
window.saveAssignment=async(btn,id)=>{const select=btn.parentElement.querySelector('select');const tags=[...select.selectedOptions].map(o=>o.value);try{await request(`${api}?assign=1`,{method:'PUT',body:JSON.stringify({object_type:$('recordType').value,record_id:id,tags})});toast('Tags updated.');await loadRecords();await loadCatalog();await loadRecent()}catch(e){toast(e.message)}};
$('tagForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('tagId').value;try{await request(id?`${api}?id=${id}`:api,{method:id?'PUT':'POST',body:JSON.stringify({name:$('tagName').value,color:$('tagColor').value})});$('tagCancel').click();toast('Tag saved.');await loadCatalog();await loadRecords()}catch(err){toast(err.message)}});
$('tagCancel').addEventListener('click',()=>{$('tagForm').reset();$('tagId').value='';$('tagColor').value='#17684e';$('tagCancel').hidden=true});$('recordType').addEventListener('change',loadRecords);$('recordSearch').addEventListener('input',renderRecords);
(async()=>{try{await loadCatalog();await loadRecords();await loadRecent()}catch(e){toast(e.message)}})();
