<?php
if(session_status()===PHP_SESSION_NONE)session_start();
header('Content-Type: application/json; charset=utf-8'); header('X-Content-Type-Options: nosniff');
function out(bool $success,$data=null,string $message='',int $code=200):void{http_response_code($code);echo json_encode(compact('success','message','data'),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if(!isset($_SESSION['user_role'])||!in_array($_SESSION['user_role'],['admin','superadmin','staff','dswd_officer'],true))out(false,null,'Unauthorized',401);
require __DIR__.'/db.php';
require __DIR__.'/street-welfare-needs-validation.php';
function auditNeed(PDO $pdo,string $action):void{$s=$pdo->prepare('INSERT INTO activity_logs(user_id,action,module,ip_address) VALUES(?,?,?,?)');$s->execute([$_SESSION['user_id']??null,$action,'Street Welfare Needs',substr($_SERVER['REMOTE_ADDR']??'unknown',0,45)]);}
function validateNeed(array $in):array{
 return validate_street_welfare_need($in);
}
$method=$_SERVER['REQUEST_METHOD']??'GET';$input=json_decode((string)file_get_contents('php://input'),true)?:[];$id=max(0,(int)($_GET['id']??0));
try{
 if($method==='GET'&&isset($_GET['meta'])){$streets=$pdo->query("SELECT s.street_id,s.street_name,s.total_households,s.total_population,COUNT(DISTINCT rr.user_id) known_residents FROM streets s LEFT JOIN resident_reports rr ON rr.street_id=s.street_id WHERE s.is_active=1 GROUP BY s.street_id ORDER BY s.street_name")->fetchAll();$people=$pdo->query("SELECT id,name,role FROM users WHERE is_active=1 AND role IN('admin','superadmin','staff','dswd_officer') ORDER BY name")->fetchAll();out(true,compact('streets','people'));}
 if($method==='GET'&&isset($_GET['summary'])){$kpi=$pdo->query("SELECT COUNT(*) total,SUM(status NOT IN('Completed','Rejected')) unresolved,SUM(priority='Urgent' AND status NOT IN('Completed','Rejected')) urgent,COALESCE(SUM(affected_households),0) households,COALESCE(SUM(affected_residents),0) residents FROM street_welfare_needs")->fetch();$streets=$pdo->query("SELECT s.street_name,COUNT(*) needs,COALESCE(SUM(n.affected_households),0) households,COALESCE(SUM(n.affected_residents),0) residents FROM street_welfare_needs n JOIN streets s ON s.street_id=n.street_id WHERE n.status NOT IN('Completed','Rejected') GROUP BY n.street_id ORDER BY needs DESC,households DESC LIMIT 8")->fetchAll();$categories=$pdo->query("SELECT category,COUNT(*) needs FROM street_welfare_needs GROUP BY category ORDER BY needs DESC")->fetchAll();out(true,compact('kpi','streets','categories'));}
 if($method==='GET'&&$id){$s=$pdo->prepare('SELECT n.*,s.street_name,u.name assigned_name FROM street_welfare_needs n JOIN streets s ON s.street_id=n.street_id LEFT JOIN users u ON u.id=n.assigned_to WHERE n.need_id=?');$s->execute([$id]);$row=$s->fetch();out((bool)$row,$row,$row?'':'Need not found.',$row?200:404);}
 if($method==='GET'){$w=['1=1'];$p=[];foreach(['street_id'=>'n.street_id','category'=>'n.category','priority'=>'n.priority','status'=>'n.status'] as $q=>$col)if(!empty($_GET[$q])){$w[]="{$col}=?";$p[]=$_GET[$q];}if(!empty($_GET['date_from'])){$w[]='n.date_reported>=?';$p[]=$_GET['date_from'];}if(!empty($_GET['date_to'])){$w[]='n.date_reported<=?';$p[]=$_GET['date_to'];}if(!empty($_GET['search'])){$w[]='(s.street_name LIKE ? OR n.description LIKE ? OR n.category LIKE ?)';$like='%'.$_GET['search'].'%';array_push($p,$like,$like,$like);}$sql='SELECT n.*,s.street_name,s.total_households,s.total_population,u.name assigned_name FROM street_welfare_needs n JOIN streets s ON s.street_id=n.street_id LEFT JOIN users u ON u.id=n.assigned_to WHERE '.implode(' AND ',$w)." ORDER BY FIELD(n.priority,'Urgent','High','Medium','Low'),n.date_reported DESC";$s=$pdo->prepare($sql);$s->execute($p);out(true,['needs'=>$s->fetchAll()]);}
 if(in_array($method,['POST','PUT'],true)){if($method==='PUT'&&!$id)out(false,null,'Need ID required.',422);$v=validateNeed($input);$dupe=$pdo->prepare("SELECT need_id FROM street_welfare_needs WHERE street_id=? AND category=? AND date_reported=? AND status NOT IN('Completed','Rejected') AND need_id<>?");$dupe->execute([$v[0],$v[1],$v[6],$id]);if($dupe->fetch())out(false,null,'A matching unresolved need already exists for this street, category, and date.',409);if($method==='POST'){$s=$pdo->prepare('INSERT INTO street_welfare_needs(street_id,category,affected_households,affected_residents,priority,description,date_reported,assigned_to,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)');$s->execute([...$v,$_SESSION['user_id']??null]);$id=(int)$pdo->lastInsertId();auditNeed($pdo,"Created street welfare need #{$id} ({$v[1]})");}else{$s=$pdo->prepare('UPDATE street_welfare_needs SET street_id=?,category=?,affected_households=?,affected_residents=?,priority=?,description=?,date_reported=?,assigned_to=?,status=? WHERE need_id=?');$s->execute([...$v,$id]);if(!$s->rowCount()){ $x=$pdo->prepare('SELECT 1 FROM street_welfare_needs WHERE need_id=?');$x->execute([$id]);if(!$x->fetch())out(false,null,'Need not found.',404);}auditNeed($pdo,"Updated street welfare need #{$id} to {$v[8]}");}out(true,['need_id'=>$id],$method==='POST'?'Need recorded.':'Need updated.');}
 if($method==='DELETE'&&$id){if(!in_array($_SESSION['user_role'],['admin','superadmin'],true))out(false,null,'Only administrators can delete needs.',403);$s=$pdo->prepare('DELETE FROM street_welfare_needs WHERE need_id=?');$s->execute([$id]);if(!$s->rowCount())out(false,null,'Need not found.',404);auditNeed($pdo,"Deleted street welfare need #{$id}");out(true,null,'Need deleted.');}
 out(false,null,'Method not allowed.',405);
}catch(InvalidArgumentException $e){out(false,null,$e->getMessage(),422);}catch(Throwable $e){error_log('[StreetWelfareNeeds] '.$e->getMessage());out(false,null,'An unexpected error occurred.',500);}
