<?php $current_page='street-welfare-needs';if(session_status()===PHP_SESSION_NONE)session_start();if(!isset($_SESSION['user_role'])||!in_array($_SESSION['user_role'],['admin','superadmin','staff','dswd_officer'],true)){header('Location: ../index.php');exit;}?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Street Welfare Needs — EQUIAID</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"><link rel="stylesheet" href="../styles/admin_sidebar.css"><link rel="stylesheet" href="../styles/admin_dashboard.css"><link rel="stylesheet" href="../styles/admin-street-welfare-needs.css"><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script></head>
<body><div class="admin-shell"><?php include 'sidebar.php';?><main class="main-content"><div class="dashboard-container">
<div class="dash-header"><div><div class="dash-breadcrumb"><i class="fa-solid fa-hand-holding-heart"></i><span>Street Welfare Needs</span></div><h1 class="dash-title">Street Welfare Needs</h1><p class="dash-desc">Identify, assess, and prioritize aggregated welfare needs without exposing household-level personal information.</p></div><button class="swn-btn" id="newNeed"><i class="fa-solid fa-plus"></i> Record Need</button></div>
<div class="swn-kpis"><div class="kpi-card"><div class="kpi-body"><span class="kpi-label">Total Needs</span><strong id="kTotal">—</strong></div></div><div class="kpi-card urgent"><div class="kpi-body"><span class="kpi-label">Urgent Unresolved</span><strong id="kUrgent">—</strong></div></div><div class="kpi-card"><div class="kpi-body"><span class="kpi-label">Unresolved</span><strong id="kOpen">—</strong></div></div><div class="kpi-card"><div class="kpi-body"><span class="kpi-label">Affected Households</span><strong id="kHouseholds">—</strong></div></div></div>
<div class="swn-charts"><section class="dash-card"><div class="card-head"><h2 class="card-title">Most Affected Streets</h2></div><div class="chart-box"><canvas id="streetChart"></canvas></div></section><section class="dash-card"><div class="card-head"><h2 class="card-title">Common Needs</h2></div><div class="chart-box"><canvas id="categoryChart"></canvas></div></section></div>
<section class="dash-card swn-table-card"><div class="card-head"><div><div class="card-label">Assessment Register</div><h2 class="card-title">Reported Needs</h2></div></div><div class="swn-filters"><input id="search" type="search" placeholder="Search street or description…"><select id="fStreet"><option value="">All Streets</option></select><select id="fCategory"><option value="">All Categories</option></select><select id="fPriority"><option value="">All Priorities</option><option>Urgent</option><option>High</option><option>Medium</option><option>Low</option></select><select id="fStatus"><option value="">All Statuses</option></select><input id="dateFrom" type="date" title="Reported from"><input id="dateTo" type="date" title="Reported to"></div><div class="table-wrap"><table class="dashboard-table"><thead><tr><th>Street</th><th>Category</th><th>Affected</th><th>Priority</th><th>Status</th><th>Reported</th><th>Assigned</th><th>Actions</th></tr></thead><tbody id="needRows"><tr><td colspan="8">Loading…</td></tr></tbody></table></div></section>
<div class="swn-modal" id="needModal" aria-hidden="true"><div class="swn-dialog"><div class="swn-modal-head"><div><small>STREET-LEVEL RECORD</small><h2 id="formTitle">Record Welfare Need</h2></div><button type="button" id="closeModal" aria-label="Close">×</button></div><form id="needForm"><input type="hidden" id="needId"><div class="swn-grid"><label>Street<select id="streetId" required></select><small id="streetSummary"></small></label><label>Category<select id="category" required></select></label><label>Affected households<input id="households" type="number" min="0" value="0" required></label><label>Affected residents<input id="residents" type="number" min="0" value="0" required></label><label>Priority<select id="priority" required><option>Urgent</option><option>High</option><option selected>Medium</option><option>Low</option></select></label><label>Status<select id="status" required></select></label><label>Date reported<input id="reported" type="date" required></label><label>Assigned personnel<select id="assigned"><option value="">Unassigned</option></select></label><label class="full">Description<textarea id="description" minlength="5" maxlength="2000" required></textarea></label></div><div class="swn-actions"><button type="button" class="swn-btn secondary" id="cancelModal">Cancel</button><button class="swn-btn" type="submit">Save Need</button></div></form></div></div><div id="swnToast" class="swn-toast"></div>
</div></main></div><script src="../js/admin-street-welfare-needs.js"></script></body></html>
